import type { AbilityAnimationConfig } from "./types";

const epicTiming = (
  overrides: Partial<AbilityAnimationConfig["timing"]> = {},
): AbilityAnimationConfig["timing"] => ({
  superFreezeDuration: 80,
  flashDuration: 220,
  textSlamDelay: 150,
  textSlamDuration: 900,
  particleBurstDelay: 250,
  totalDuration: 1400,
  ...overrides,
});

const legendaryTiming = (
  overrides: Partial<AbilityAnimationConfig["timing"]> = {},
): AbilityAnimationConfig["timing"] => ({
  superFreezeDuration: 160,
  flashDuration: 600,
  textSlamDelay: 400,
  textSlamDuration: 1400,
  particleBurstDelay: 600,
  totalDuration: 2800,
  ...overrides,
});

export const CARD_ANIMATION_CONFIGS: Record<string, AbilityAnimationConfig> = {
  // ═══════════════ DONALD RUMPF EPIC ═══════════════
  "dr-executive": {
    cardId: "dr-executive",
    rarity: "epic",
    characterId: "donald-rumpf",
    timing: epicTiming(),
    visual: {
      flashColor: "#1A3A6B",
      flashSecondaryColor: "#B22234",
      impactLineColor: "#FFFFFF",
      impactLineCount: 16,
      impactLineWeight: 1.5,
      particleColor: "#FFD700",
      particleCount: 90,
      particlePattern: "radial",
      textStyle: "objection",
      characterAnimationType: "point",
    },
  },
  "dr-trade-war": {
    cardId: "dr-trade-war",
    rarity: "epic",
    characterId: "donald-rumpf",
    timing: epicTiming({
      flashDuration: 200,
      textSlamDelay: 140,
      textSlamDuration: 850,
      particleBurstDelay: 220,
      totalDuration: 1350,
    }),
    visual: {
      flashColor: "#B22234",
      flashSecondaryColor: "#1A3A6B",
      impactLineColor: "#FFD700",
      impactLineCount: 12,
      impactLineWeight: 1.2,
      particleColor: "#FFD700",
      particleCount: 75,
      particlePattern: "spiral",
      textStyle: "announce",
      characterAnimationType: "slam",
    },
  },
  "dr-veto": {
    cardId: "dr-veto",
    rarity: "epic",
    characterId: "donald-rumpf",
    timing: epicTiming({
      flashDuration: 250,
      textSlamDelay: 160,
      textSlamDuration: 950,
      particleBurstDelay: 280,
      totalDuration: 1450,
    }),
    visual: {
      flashColor: "#FFFFFF",
      flashSecondaryColor: "#1A3A6B",
      impactLineColor: "#1A3A6B",
      impactLineCount: 20,
      impactLineWeight: 2.0,
      particleColor: "#FFFFFF",
      particleCount: 100,
      particlePattern: "shockwave",
      textStyle: "impact",
      characterAnimationType: "shield",
    },
  },
  "dr-fire": {
    cardId: "dr-fire",
    rarity: "epic",
    characterId: "donald-rumpf",
    timing: epicTiming({
      flashDuration: 200,
      textSlamDelay: 130,
      textSlamDuration: 800,
      particleBurstDelay: 200,
      totalDuration: 1300,
    }),
    visual: {
      flashColor: "#FF4500",
      flashSecondaryColor: "#FFD700",
      impactLineColor: "#FF6600",
      impactLineCount: 14,
      impactLineWeight: 1.5,
      particleColor: "#FF4500",
      particleCount: 85,
      particlePattern: "explosion",
      textStyle: "objection",
      characterAnimationType: "point",
    },
  },
  "dr-impeach": {
    cardId: "dr-impeach",
    rarity: "epic",
    characterId: "donald-rumpf",
    timing: epicTiming({
      flashDuration: 220,
      textSlamDelay: 150,
      textSlamDuration: 900,
      particleBurstDelay: 230,
      totalDuration: 1400,
    }),
    visual: {
      flashColor: "#8B0000",
      flashSecondaryColor: "#1A3A6B",
      impactLineColor: "#FF4444",
      impactLineCount: 18,
      impactLineWeight: 1.8,
      particleColor: "#8B0000",
      particleCount: 95,
      particlePattern: "radial",
      textStyle: "announce",
      characterAnimationType: "slam",
    },
  },

  // ═══════════════ VLADIMIR PU EPIC ═══════════════
  "vp-bear": {
    cardId: "vp-bear",
    rarity: "epic",
    characterId: "vladimir-pu",
    timing: epicTiming({
      flashDuration: 240,
      textSlamDelay: 160,
      textSlamDuration: 950,
      particleBurstDelay: 260,
      totalDuration: 1450,
    }),
    visual: {
      flashColor: "#CC0000",
      flashSecondaryColor: "#8B0000",
      impactLineColor: "#CC0000",
      impactLineCount: 20,
      impactLineWeight: 2.5,
      particleColor: "#CC0000",
      particleCount: 110,
      particlePattern: "shockwave",
      textStyle: "impact",
      characterAnimationType: "charge",
    },
  },
  "vp-nerve": {
    cardId: "vp-nerve",
    rarity: "epic",
    characterId: "vladimir-pu",
    timing: epicTiming({
      flashDuration: 300,
      textSlamDelay: 200,
      textSlamDuration: 1000,
      particleBurstDelay: 300,
      totalDuration: 1500,
    }),
    visual: {
      flashColor: "#4A9B4A",
      flashSecondaryColor: "#1A4A1A",
      impactLineColor: "#7FFF00",
      impactLineCount: 16,
      impactLineWeight: 1.5,
      particleColor: "#7FFF00",
      particleCount: 120,
      particlePattern: "rain",
      textStyle: "announce",
      characterAnimationType: "point",
    },
  },
  "vp-fortress": {
    cardId: "vp-fortress",
    rarity: "epic",
    characterId: "vladimir-pu",
    timing: epicTiming({
      flashDuration: 250,
      textSlamDelay: 160,
      textSlamDuration: 900,
      particleBurstDelay: 250,
      totalDuration: 1400,
    }),
    visual: {
      flashColor: "#4A4A88",
      flashSecondaryColor: "#1A1A44",
      impactLineColor: "#AAAAFF",
      impactLineCount: 24,
      impactLineWeight: 1.0,
      particleColor: "#AAAAFF",
      particleCount: 80,
      particlePattern: "shockwave",
      textStyle: "impact",
      characterAnimationType: "shield",
    },
  },
  "vp-special-op": {
    cardId: "vp-special-op",
    rarity: "epic",
    characterId: "vladimir-pu",
    timing: epicTiming({
      flashDuration: 220,
      textSlamDelay: 140,
      textSlamDuration: 880,
      particleBurstDelay: 220,
      totalDuration: 1380,
    }),
    visual: {
      flashColor: "#CC0000",
      flashSecondaryColor: "#660000",
      impactLineColor: "#FF2200",
      impactLineCount: 22,
      impactLineWeight: 2.0,
      particleColor: "#FF4400",
      particleCount: 100,
      particlePattern: "explosion",
      textStyle: "impact",
      characterAnimationType: "slam",
    },
  },
  "vp-cyber": {
    cardId: "vp-cyber",
    rarity: "epic",
    characterId: "vladimir-pu",
    timing: epicTiming({
      flashDuration: 200,
      textSlamDelay: 130,
      textSlamDuration: 820,
      particleBurstDelay: 200,
      totalDuration: 1320,
    }),
    visual: {
      flashColor: "#00FF88",
      flashSecondaryColor: "#003322",
      impactLineColor: "#00FF88",
      impactLineCount: 14,
      impactLineWeight: 1.2,
      particleColor: "#00FF88",
      particleCount: 85,
      particlePattern: "rain",
      textStyle: "announce",
      characterAnimationType: "point",
    },
  },

  // ═══════════════ JIN SHI EPIC ═══════════════
  "js-dragon": {
    cardId: "js-dragon",
    rarity: "epic",
    characterId: "jin-shi",
    timing: epicTiming({
      flashDuration: 280,
      textSlamDelay: 180,
      textSlamDuration: 1000,
      particleBurstDelay: 280,
      totalDuration: 1480,
    }),
    visual: {
      flashColor: "#DE2910",
      flashSecondaryColor: "#FFDE00",
      impactLineColor: "#FFDE00",
      impactLineCount: 20,
      impactLineWeight: 2.2,
      particleColor: "#FF6600",
      particleCount: 130,
      particlePattern: "spiral",
      textStyle: "impact",
      characterAnimationType: "rise",
    },
  },
  "js-bri": {
    cardId: "js-bri",
    rarity: "epic",
    characterId: "jin-shi",
    timing: epicTiming({
      flashDuration: 220,
      textSlamDelay: 150,
      textSlamDuration: 900,
      particleBurstDelay: 240,
      totalDuration: 1400,
    }),
    visual: {
      flashColor: "#FFDE00",
      flashSecondaryColor: "#DE2910",
      impactLineColor: "#FFD700",
      impactLineCount: 16,
      impactLineWeight: 1.5,
      particleColor: "#FFDE00",
      particleCount: 90,
      particlePattern: "radial",
      textStyle: "announce",
      characterAnimationType: "slam",
    },
  },
  "js-propaganda": {
    cardId: "js-propaganda",
    rarity: "epic",
    characterId: "jin-shi",
    timing: epicTiming({
      flashDuration: 240,
      textSlamDelay: 160,
      textSlamDuration: 940,
      particleBurstDelay: 260,
      totalDuration: 1440,
    }),
    visual: {
      flashColor: "#CC1100",
      flashSecondaryColor: "#880000",
      impactLineColor: "#FF0000",
      impactLineCount: 18,
      impactLineWeight: 1.8,
      particleColor: "#FF0000",
      particleCount: 100,
      particlePattern: "radial",
      textStyle: "objection",
      characterAnimationType: "point",
    },
  },
  "js-censure": {
    cardId: "js-censure",
    rarity: "epic",
    characterId: "jin-shi",
    timing: epicTiming({
      flashDuration: 200,
      textSlamDelay: 130,
      textSlamDuration: 820,
      particleBurstDelay: 210,
      totalDuration: 1320,
    }),
    visual: {
      flashColor: "#8B0000",
      flashSecondaryColor: "#1A0000",
      impactLineColor: "#CC0000",
      impactLineCount: 14,
      impactLineWeight: 1.3,
      particleColor: "#8B0000",
      particleCount: 70,
      particlePattern: "explosion",
      textStyle: "impact",
      characterAnimationType: "slam",
    },
  },

  // ═══════════════ VLADO ZELENKO EPIC ═══════════════
  "vz-counteroffensive": {
    cardId: "vz-counteroffensive",
    rarity: "epic",
    characterId: "vlado-zelenko",
    timing: epicTiming({
      flashDuration: 200,
      textSlamDelay: 120,
      textSlamDuration: 800,
      particleBurstDelay: 200,
      totalDuration: 1300,
    }),
    visual: {
      flashColor: "#005BBB",
      flashSecondaryColor: "#FFD500",
      impactLineColor: "#FFD500",
      impactLineCount: 18,
      impactLineWeight: 1.8,
      particleColor: "#FFD500",
      particleCount: 110,
      particlePattern: "explosion",
      textStyle: "objection",
      characterAnimationType: "charge",
    },
  },
  "vz-bradley": {
    cardId: "vz-bradley",
    rarity: "epic",
    characterId: "vlado-zelenko",
    timing: epicTiming({
      flashDuration: 210,
      textSlamDelay: 130,
      textSlamDuration: 840,
      particleBurstDelay: 210,
      totalDuration: 1340,
    }),
    visual: {
      flashColor: "#556B2F",
      flashSecondaryColor: "#8B6914",
      impactLineColor: "#CCAA44",
      impactLineCount: 16,
      impactLineWeight: 2.0,
      particleColor: "#8B6914",
      particleCount: 90,
      particlePattern: "shockwave",
      textStyle: "impact",
      characterAnimationType: "slam",
    },
  },
  "vz-azov": {
    cardId: "vz-azov",
    rarity: "epic",
    characterId: "vlado-zelenko",
    timing: epicTiming({
      flashDuration: 260,
      textSlamDelay: 170,
      textSlamDuration: 960,
      particleBurstDelay: 270,
      totalDuration: 1460,
    }),
    visual: {
      flashColor: "#005BBB",
      flashSecondaryColor: "#FFFFFF",
      impactLineColor: "#FFFFFF",
      impactLineCount: 22,
      impactLineWeight: 2.5,
      particleColor: "#FFFFFF",
      particleCount: 100,
      particlePattern: "shockwave",
      textStyle: "impact",
      characterAnimationType: "shield",
    },
  },
  "vz-zelensky-on-air": {
    cardId: "vz-zelensky-on-air",
    rarity: "epic",
    characterId: "vlado-zelenko",
    timing: epicTiming({
      flashDuration: 200,
      textSlamDelay: 120,
      textSlamDuration: 800,
      particleBurstDelay: 200,
      totalDuration: 1300,
    }),
    visual: {
      flashColor: "#00AAFF",
      flashSecondaryColor: "#0055AA",
      impactLineColor: "#00AAFF",
      impactLineCount: 14,
      impactLineWeight: 1.2,
      particleColor: "#00AAFF",
      particleCount: 80,
      particlePattern: "radial",
      textStyle: "announce",
      characterAnimationType: "point",
    },
  },

  // ═══════════════ RUMPF LEGENDARY ═══════════════
  "dr-nuclear": {
    cardId: "dr-nuclear",
    rarity: "legendary",
    characterId: "donald-rumpf",
    timing: legendaryTiming(),
    visual: {
      flashColor: "#FF6600",
      flashSecondaryColor: "#FF2200",
      impactLineColor: "#FFFF00",
      impactLineCount: 32,
      impactLineWeight: 4.0,
      particleColor: "#FF6600",
      particleCount: 250,
      particlePattern: "explosion",
      textStyle: "impact",
      characterAnimationType: "slam",
    },
    uniqueEffect: "mushroom_cloud",
  },
  "dr-twitter-ban": {
    cardId: "dr-twitter-ban",
    rarity: "legendary",
    characterId: "donald-rumpf",
    timing: legendaryTiming({
      flashDuration: 500,
      textSlamDelay: 350,
      textSlamDuration: 1300,
      particleBurstDelay: 550,
      totalDuration: 2700,
    }),
    visual: {
      flashColor: "#1DA1F2",
      flashSecondaryColor: "#000000",
      impactLineColor: "#1DA1F2",
      impactLineCount: 28,
      impactLineWeight: 3.0,
      particleColor: "#1DA1F2",
      particleCount: 200,
      particlePattern: "spiral",
      textStyle: "objection",
      characterAnimationType: "point",
    },
    uniqueEffect: "screen_blackout",
  },
  "dr-maga-phoenix": {
    cardId: "dr-maga-phoenix",
    rarity: "legendary",
    characterId: "donald-rumpf",
    timing: legendaryTiming({
      flashDuration: 700,
      textSlamDelay: 450,
      textSlamDuration: 1500,
      particleBurstDelay: 650,
      totalDuration: 3000,
    }),
    visual: {
      flashColor: "#FF4500",
      flashSecondaryColor: "#FFD700",
      impactLineColor: "#FF8800",
      impactLineCount: 30,
      impactLineWeight: 3.5,
      particleColor: "#FF6600",
      particleCount: 280,
      particlePattern: "spiral",
      textStyle: "announce",
      characterAnimationType: "rise",
    },
    uniqueEffect: "phoenix_rise",
  },

  // ═══════════════ PU LEGENDARY ═══════════════
  "vp-sovereign": {
    cardId: "vp-sovereign",
    rarity: "legendary",
    characterId: "vladimir-pu",
    timing: legendaryTiming({
      flashDuration: 650,
      textSlamDelay: 420,
      textSlamDuration: 1450,
      particleBurstDelay: 620,
      totalDuration: 2900,
    }),
    visual: {
      flashColor: "#CC0000",
      flashSecondaryColor: "#880000",
      impactLineColor: "#FF2200",
      impactLineCount: 36,
      impactLineWeight: 5.0,
      particleColor: "#CC0000",
      particleCount: 300,
      particlePattern: "explosion",
      textStyle: "impact",
      characterAnimationType: "charge",
    },
    uniqueEffect: "mushroom_cloud",
  },
  "vp-eternal": {
    cardId: "vp-eternal",
    rarity: "legendary",
    characterId: "vladimir-pu",
    timing: legendaryTiming({
      flashDuration: 550,
      textSlamDelay: 380,
      textSlamDuration: 1350,
      particleBurstDelay: 560,
      totalDuration: 2700,
    }),
    visual: {
      flashColor: "#D4AF37",
      flashSecondaryColor: "#1A0000",
      impactLineColor: "#D4AF37",
      impactLineCount: 24,
      impactLineWeight: 3.0,
      particleColor: "#D4AF37",
      particleCount: 220,
      particlePattern: "radial",
      textStyle: "announce",
      characterAnimationType: "rise",
    },
    uniqueEffect: "clock_freeze",
  },
  "vp-bearmode": {
    cardId: "vp-bearmode",
    rarity: "legendary",
    characterId: "vladimir-pu",
    timing: legendaryTiming(),
    visual: {
      flashColor: "#4A1A00",
      flashSecondaryColor: "#CC0000",
      impactLineColor: "#885500",
      impactLineCount: 28,
      impactLineWeight: 4.5,
      particleColor: "#885500",
      particleCount: 250,
      particlePattern: "shockwave",
      textStyle: "impact",
      characterAnimationType: "charge",
    },
    uniqueEffect: "bear_roar",
  },

  // ═══════════════ JIN SHI LEGENDARY ═══════════════
  "js-emperor": {
    cardId: "js-emperor",
    rarity: "legendary",
    characterId: "jin-shi",
    timing: legendaryTiming({
      flashDuration: 700,
      textSlamDelay: 450,
      textSlamDuration: 1500,
      particleBurstDelay: 680,
      totalDuration: 3000,
    }),
    visual: {
      flashColor: "#FFDE00",
      flashSecondaryColor: "#DE2910",
      impactLineColor: "#FFD700",
      impactLineCount: 30,
      impactLineWeight: 3.5,
      particleColor: "#FFD700",
      particleCount: 280,
      particlePattern: "spiral",
      textStyle: "announce",
      characterAnimationType: "rise",
    },
    uniqueEffect: "dragon_rise",
  },
  "js-eternal-rule": {
    cardId: "js-eternal-rule",
    rarity: "legendary",
    characterId: "jin-shi",
    timing: legendaryTiming(),
    visual: {
      flashColor: "#DE2910",
      flashSecondaryColor: "#FFDE00",
      impactLineColor: "#FF0000",
      impactLineCount: 32,
      impactLineWeight: 4.0,
      particleColor: "#DE2910",
      particleCount: 260,
      particlePattern: "radial",
      textStyle: "impact",
      characterAnimationType: "slam",
    },
    uniqueEffect: "great_wall",
  },
  "js-century": {
    cardId: "js-century",
    rarity: "legendary",
    characterId: "jin-shi",
    timing: legendaryTiming({
      flashDuration: 650,
      textSlamDelay: 420,
      textSlamDuration: 1450,
      particleBurstDelay: 640,
      totalDuration: 2900,
    }),
    visual: {
      flashColor: "#FFD700",
      flashSecondaryColor: "#DE2910",
      impactLineColor: "#FFD700",
      impactLineCount: 28,
      impactLineWeight: 3.5,
      particleColor: "#FF8800",
      particleCount: 240,
      particlePattern: "explosion",
      textStyle: "announce",
      characterAnimationType: "rise",
    },
    uniqueEffect: "dragon_fire",
  },
  "js-dragon-fire": {
    cardId: "js-dragon-fire",
    rarity: "legendary",
    characterId: "jin-shi",
    timing: legendaryTiming({
      flashDuration: 580,
      textSlamDelay: 380,
      textSlamDuration: 1380,
      particleBurstDelay: 580,
      totalDuration: 2760,
    }),
    visual: {
      flashColor: "#FF6600",
      flashSecondaryColor: "#FFDE00",
      impactLineColor: "#FF4400",
      impactLineCount: 26,
      impactLineWeight: 3.8,
      particleColor: "#FF4400",
      particleCount: 230,
      particlePattern: "explosion",
      textStyle: "impact",
      characterAnimationType: "charge",
    },
    uniqueEffect: "dragon_fire",
  },

  // ═══════════════ ZELENKO LEGENDARY ═══════════════
  "vz-slava": {
    cardId: "vz-slava",
    rarity: "legendary",
    characterId: "vlado-zelenko",
    timing: legendaryTiming({
      flashDuration: 550,
      textSlamDelay: 360,
      textSlamDuration: 1350,
      particleBurstDelay: 560,
      totalDuration: 2700,
    }),
    visual: {
      flashColor: "#005BBB",
      flashSecondaryColor: "#FFD500",
      impactLineColor: "#FFD500",
      impactLineCount: 26,
      impactLineWeight: 3.0,
      particleColor: "#FFD500",
      particleCount: 220,
      particlePattern: "shockwave",
      textStyle: "objection",
      characterAnimationType: "charge",
    },
    uniqueEffect: "ukraine_flag",
  },
  "vz-iron-resolve": {
    cardId: "vz-iron-resolve",
    rarity: "legendary",
    characterId: "vlado-zelenko",
    timing: legendaryTiming(),
    visual: {
      flashColor: "#FFFFFF",
      flashSecondaryColor: "#005BBB",
      impactLineColor: "#FFFFFF",
      impactLineCount: 30,
      impactLineWeight: 2.5,
      particleColor: "#FFFFFF",
      particleCount: 240,
      particlePattern: "radial",
      textStyle: "impact",
      characterAnimationType: "rise",
    },
    uniqueEffect: "iron_shield",
  },
  "vz-trident": {
    cardId: "vz-trident",
    rarity: "legendary",
    characterId: "vlado-zelenko",
    timing: legendaryTiming({
      flashDuration: 620,
      textSlamDelay: 410,
      textSlamDuration: 1420,
      particleBurstDelay: 610,
      totalDuration: 2820,
    }),
    visual: {
      flashColor: "#005BBB",
      flashSecondaryColor: "#FFD500",
      impactLineColor: "#FFD500",
      impactLineCount: 34,
      impactLineWeight: 4.0,
      particleColor: "#FFD500",
      particleCount: 270,
      particlePattern: "explosion",
      textStyle: "impact",
      characterAnimationType: "slam",
    },
    uniqueEffect: "trident_strike",
  },
  "vz-freedom": {
    cardId: "vz-freedom",
    rarity: "legendary",
    characterId: "vlado-zelenko",
    timing: legendaryTiming({
      flashDuration: 700,
      textSlamDelay: 450,
      textSlamDuration: 1500,
      particleBurstDelay: 680,
      totalDuration: 3000,
    }),
    visual: {
      flashColor: "#FFD500",
      flashSecondaryColor: "#005BBB",
      impactLineColor: "#FFFFFF",
      impactLineCount: 32,
      impactLineWeight: 3.5,
      particleColor: "#FFD500",
      particleCount: 300,
      particlePattern: "radial",
      textStyle: "announce",
      characterAnimationType: "rise",
    },
    uniqueEffect: "freedom_wave",
  },
};

export function getCardAnimationConfig(
  cardId: string,
): AbilityAnimationConfig | undefined {
  return CARD_ANIMATION_CONFIGS[cardId.split("#")[0]];
}
