import { writeFile, mkdir } from "fs/promises";
import path from "path";
import {
  MASTER_PREFIX,
  PORTRAIT_TECH,
  CARD_TECH,
  MASTER_NEGATIVE,
  FACTION_PHRASE,
  PORTRAITS,
  DONALD_CARDS,
  VLADIMIR_CARDS,
  JIN_CARDS,
  VLADO_CARDS,
  NEUTRAL_CARDS,
  SHARED_ASSETS,
  ARENA_LAYERS,
  buildPrompt,
  type LockedAsset,
} from "../lib/game/locked-prompts";

const OUT = path.join(process.cwd(), "public", "placeholders", "PROMPTS.LOCKED.md");

function section(title: string, assets: LockedAsset[]): string {
  const lines: string[] = [`## ${title}`, ""];
  for (const asset of assets) {
    lines.push(`### \`${asset.id}\``);
    lines.push(`- **File:** \`${asset.file}\``);
    lines.push(`- **Size:** ${asset.width}×${asset.height}${asset.alpha ? " RGBA" : " opaque"}`);
    if (asset.faction) lines.push(`- **Faction:** ${asset.faction}`);
    if (asset.rarity) lines.push(`- **Rarity optics:** ${asset.rarity}`);
    lines.push(`- **Prompt (EN):**`);
    lines.push(`  ${buildPrompt(asset)}`);
    lines.push(`- **Negative:**`);
    lines.push(`  \`${MASTER_NEGATIVE}\``);
    lines.push("");
  }
  return lines.join("\n");
}

async function main(): Promise<void> {
  await mkdir(path.dirname(OUT), { recursive: true });

  const content = [
    "# WORLD ORDER — PROMPTS.LOCKED (Critic-APPROVED)",
    "",
    "> Style Bible v1.0 · English only · Three.js cutout-ready · Do not regenerate with mechanics text.",
    "> Generated by `tsx scripts/write-prompts-locked.ts`",
    "",
    "## Style Bible",
    "",
    "**Master prefix (verbatim first sentence):**",
    "```",
    MASTER_PREFIX,
    "```",
    "",
    "**Portrait tech:**",
    "```",
    PORTRAIT_TECH,
    "```",
    "",
    "**Card tech:**",
    "```",
    CARD_TECH,
    "```",
    "",
    "**Master negative:**",
    "```",
    MASTER_NEGATIVE,
    "```",
    "",
    "**Faction lock phrases:**",
    "",
    "| Faction | Phrase |",
    "|---|---|",
    ...Object.entries(FACTION_PHRASE).map(([id, phrase]) => `| \`${id}\` | ${phrase} |`),
    "",
    "**Forbidden:** HP, energy, armor, damage numbers, `+N`, card tiles, heal/revive/DOT as rules jargon.",
    "",
    "**Rarity optics:** common flat → rare cool blue rim → epic violet veins → legendary hot orange-gold.",
    "",
    section("Portraits (12)", PORTRAITS),
    section("Donald Rumpf cards (20)", DONALD_CARDS),
    section("Vladimir Pu cards (20)", VLADIMIR_CARDS),
    section("Jin Shi cards (20)", JIN_CARDS),
    section("Vlado Zelenko cards (20)", VLADO_CARDS),
    section("Neutral cards — Global Resolutions (24)", NEUTRAL_CARDS),
    section("Shared (6)", SHARED_ASSETS),
    section("Arena layers — TZ stretch (20)", ARENA_LAYERS),
    "## Totals",
    "",
    "| Category | Count |",
    "|---|---|",
    "| Portraits | 12 |",
    "| Faction cards | 80 |",
    "| Neutral cards | 24 |",
    "| Shared | 6 |",
    "| Core | **122** |",
    "| Arena layers (optional) | 20 |",
    "| **All** | **142** |",
    "",
    "**APPROVED — ready to generate pixels.**",
    "",
  ].join("\n");

  await writeFile(OUT, content, "utf-8");
  const prompts = (content.match(/\*\*Prompt \(EN\):\*\*/g) ?? []).length;
  console.log(`Written ${OUT}`);
  console.log(`Prompt sections: ${prompts}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
